# Generated by Django 4.1.3 on 2022-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="size",
            field=models.CharField(default="sml", max_length=3),
        ),
    ]
