# Generated by Django 4.1.3 on 2022-11-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0002_animal_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="age",
            field=models.IntegerField(default=1),
        ),
    ]
